name: meechoke_project
description: a MeeChoke mobile application project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  cupertino_icons: ^1.0.5
  responsive_framework: ^1.1.0
  page_transition: ^2.0.9
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  shared_preferences: ^2.0.15
  device_info_plus: ^8.1.0
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/main_menu/
    - assets/images/
 
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Light.ttf
